name: Add storybook testing results links to pull request
on:
  workflow_run:
    workflows:
      - Storybook testing CI flow
    types:
      - completed

jobs:
  artifacts-url-comments:
    name: Add storybook testing results links to pull request
    runs-on: ubuntu-latest
    steps:
      - name: Add artifact links to pull request
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          prefix: 'Storybook testing artifacts: '
          suffix: Or check GH Action `Storybook testing CI flow` for more logs.
          format: '- [{name}]({url});'
          addTo: pull
          errorNoArtifacts: 'false'