name: UI app unit testing CI flow
on:
  pull_request:
    branches:
      - develop

jobs:
  base_branch_coverage_check:
    name: Generate base branch tests coverage report
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.3

      - name: Cache Node Modules for ui-app
        id: cache-node-modules-base-ui-app
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-base-ui-app-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies for ui-app
        if: steps.cache-node-modules-base-ui-app.outputs.cache-hit != 'true'
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:ci --collectCoverageFrom="./src/**" --coverage

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v2
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info

  unit_testing:
    name: Build UI application
    runs-on: macos-11
    needs: base_branch_coverage_check
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.3

      - uses: actions/checkout@v2

      - name: Download code coverage report from base branch
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: ref-lcov.info

      - name: Cache Node Modules for ui-app
        id: cache-node-modules-ui-app
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-ui-app-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies for ui-app
        if: steps.cache-node-modules-ui-app.outputs.cache-hit != 'true'
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:ci

      - name: Upload unit tests report file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ci-unit-tests-results
          path: ./ui-app-unit-tests-results.html

      - name: Post coverage report in PR
        id: code-coverage
        continue-on-error: true
        uses: barecheck/code-coverage-action@v0.5.1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./lcov.info"
          send-summary-comment: true
          show-annotations: "warning"
