name: App E2E testing
on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'

jobs:
  build-app-storybook:
    name: Build App and Storybook
    uses: ./.github/workflows/_called_build-app-and-storybook.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  app-e2e-tests:
    name: Run App e2e tests
    needs: build-app-storybook
    uses: ./.github/workflows/_called_run-app-e2e-tests.yml
    if: ${{ needs.build-app-storybook.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app
