# | Run E2E test for UI Application

name: 'E2E testing App'

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  build:
    name: 'Build'
    uses: ./.github/workflows/_called_build.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  app-e2e-tests:
    name: 'Run tests'
    needs: build
    uses: ./.github/workflows/_called_run-e2e-tests-app.yml
    if: ${{ needs.build.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  report-statuses-in-issue:
    # | Publish build and deployment statuses as pull request comment,
    # | if any pull request is associated with triggered commit.
    name: 'Report in PR'
    uses: ./.github/workflows/_called_report-status-in-issue.yml
    if: ${{ always() && needs.build.result != 'cancelled' && needs.app-e2e-tests.result != 'cancelled' }}
    needs: [build, app-e2e-tests]
    with:
      publish-artifacts-list: true

      app-e2e-test-pub-report: true
      app-e2e-test-status: ${{ needs.app-e2e-tests.result == 'success' }}

      app-storybook-build-pub-report: false
      app-storybook-deploy-pub-report: false
      app-unit-test-pub-report: false

    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
      gh_pages_custom_domain: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}
