# | Run E2E test for UI Application

name: "E2E testing App"

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/_called_build.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  app-e2e-tests:
    name: "Run tests"
    needs: build
    uses: ./.github/workflows/_called_run-e2e-tests-app.yml
    if: ${{ needs.build.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app
