# | Build Application and Storybook. Deploy builds into GihHub Pages. Publish build and deployment statuses as
# | pull request comment, if any pull request is associated with latest commit.

name: "Build Deploy Report"

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  build:
    # | Build Application and Storybook.
    name: "Build"
    uses: ./.github/workflows/_called_build.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  deploy:
    # | Deploy Application and Storybook into GitHub Pages. Folder name is the same as working branch.
    name: "Deploy"
    needs: build
    uses: ./.github/workflows/_called_deploy.yml
    if: ${{ needs.build.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}

  report-statuses-in-issue:
    # | Publish build and deployment statuses as pull request comment,
    # | if any pull request is associated with the latest commit.
    name: "Report in issue"
    uses: ./.github/workflows/_called_report-status-in-issue.yml
    if: always()
    needs: [ build, deploy ]
    with:
      report-msg-title: "Basilisk-UI build reporter"
      publish-artifacts-list: true

      app-storybook-build-pub-report: true
      app-storybook-build-status: ${{ needs.build.result == 'success' }}

      app-storybook-deploy-pub-report: true
      app-storybook-deploy-status: ${{ needs.deploy.result == 'success' }}

      app-unit-test-pub-report: false
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
      gh_pages_custom_domain: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}