name: Build Deploy App and Storybook
on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  build-app-storybook:
    name: Build App and Storybook
    uses: ./.github/workflows/_called_build-app-and-storybook.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  deploy-app-storybook-builds:
    name: Deploy App&Storybook builds
    needs: build-app-storybook
    uses: ./.github/workflows/_called_deploy-app-and-storybook.yml
    if: ${{ needs.build-app-storybook.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}

  report-statuses-issue-comment:
    name: Reportr issue comment
    uses: ./.github/workflows/_called_publish-report-issue-comment.yml
    if: ${{ always() }}
    needs: [ build-app-storybook, deploy-app-storybook-builds ]
    with:
      report-msg-title: Basilisk-UI build reporter
      publish-artifacts-list: true

      app-build-pub-report: true
      app-build-status: ${{ needs.build-app-storybook.result == 'success' }}

      app-sb-deploy-pub-report: true
      app-sb-deploy-status: ${{ needs.deploy-app-storybook-builds.result == 'success' }}

      app-unit-test-pub-report: false
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
      gh_pages_custom_domain: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}