name: Build Deploy App and Storybook
on:
  push:
    branches:
      - develop
      - 'fix/**'
      - 'feat/**'
  pull_request:
    branches:
      - 'fix/**'
      - 'feat/**'

jobs:
  build-app-storybook:
    name: Build App and Storybook
    uses: ./.github/workflows/_called_build-app-and-storybook.yml
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
      app-node-modules-cache-key: cache-node-modules-ui-app

  deploy-app-storybook-builds:
    name: Deploy App&Storybook builds
    needs: build-app-storybook
    uses: ./.github/workflows/_called_deploy-app-and-storybook.yml
    if: ${{ needs.build-app-storybook.result=='success' }}
    with:
      app-build-artifact-name: app-build-files
      storybook-build-artifact-name: sb-build-files
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
